language: go

sudo: required

go:
  - 1.14.x

env:
  global:
    - OPERATOR_NAME=grafana-operator

stages:
  - test
  - compile
  - name: push
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      script:
        - set -e
        - make setup/travis code/check test/unit
    - stage: compile
      script:
        - set -e
        - make setup/travis image/build
    - stage: push
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make setup/travis image/build/push
