{
 "title": "gRPC Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(go_memstats_alloc_bytes,job)"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "le",
    "query": "\"0.1\",\"0.15\",\"0.25\",\"0.3\",\"0.5\",\"1\""
   },
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "chart",
    "label": "Chart",
    "query": "label_values(grpc_server_handled_total,app_kubernetes_io_instance)"
   },
   {
    "name": "grpc_service",
    "label": "grpc_service",
    "query": "label_values(grpc_server_handled_total{app_kubernetes_io_instance=\"$chart\"},grpc_service)"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Permission Denied Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(\n(sum(rate(grpc_server_handled_total{app_kubernetes_io_instance=\"$chart\",grpc_type=\"unary\",grpc_code=\"PermissionDenied\"}[5m])))\n/ \nsum(rate(grpc_server_started_total{app_kubernetes_io_instance=\"$chart\",grpc_type=\"unary\"}[5m]))\n, .01)"
    }
   ]
  },
  {
   "title": "Global Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handled_total{app_kubernetes_io_instance=\"$chart\",grpc_type=~\"bidi_stream|unary\",grpc_code=\"OK\"}[$interval])) + \nsum(rate(grpc_server_handled_total{app_kubernetes_io_instance=\"$chart\",grpc_type=~\"bidi_stream|unary\",grpc_code=\"NotFound\"}[$interval])) + \nsum(rate(grpc_server_handled_total{app_kubernetes_io_instance=\"$chart\",grpc_type=~\"bidi_stream|unary\",grpc_code=\"PermissionDenied\"}[$interval])) + \nsum(rate(grpc_server_handled_total{app_kubernetes_io_instance=\"$chart\",grpc_type=~\"bidi_stream|unary\",grpc_code=\"InvalidArgument\"}[$interval])))\n/ \nsum(rate(grpc_server_started_total{app_kubernetes_io_instance=\"$chart\",grpc_type=~\"bidi_stream|unary\"}[$interval]))"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{app_kubernetes_io_instance=\"$chart\"}[$interval]))"
    }
   ]
  },
  {
   "title": "gRPC request code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{app_kubernetes_io_instance=\"$chart\",grpc_type=~\"bidi_stream|unary\"}[$interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{app_kubernetes_io_instance=\"$chart\",grpc_service=~\"$grpc_service\"}[30m])) by (le, grpc_service, grpc_method)) > 1"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app_kubernetes_io_instance=\"$chart\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Aggregate Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{app_kubernetes_io_instance=\"$chart\"}) by (app_kubernetes_io_component)",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\",app_kubernetes_io_instance=\"$chart\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\",app_kubernetes_io_instance=\"$chart\"}",
     "legendFormat": "{{kubernetes_pod_name}}, {{quantile}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=~\".+\",container_name!=\"POD\",namespace=\"$chart\"}[5m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\",app_kubernetes_io_instance=\"$chart\"}",
     "legendFormat": "bytes allocated"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{app_kubernetes_io_instance=\"$chart\"}[$interval])) by (grpc_service)",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Average Handling $grpc_service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(grpc_server_handling_seconds_sum{app_kubernetes_io_instance=\"$chart\",grpc_service=~\"$grpc_service\",grpc_type=\"unary\"}[$interval]) / rate(grpc_server_handling_seconds_count{app_kubernetes_io_instance=\"$chart\",grpc_service=~\"$grpc_service\",grpc_type=\"unary\"}[$interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  }
 ]
}